'use server';
import React from "react";
import "./globals.scss";
import "../../public/theme/themes/tailwind/tailwind-light/theme.scss";
import 'sweetalert2/src/sweetalert2.scss'
import {Toaster} from "react-hot-toast";
import {SessionProvider} from "next-auth/react";
import SessionExpirationWatcher from "@/lib/SessionExpirationWatcher";
import SplashScreenLayout from "@/shared-components/SplashScreenLayout";
import {auth} from "@/auth";

// export const metadata: Metadata = {
//     title: 'My App',
//     description: 'Generated by Next.js',
// };

const RootLayout = async ({ children, }: { children: React.ReactNode; }) => {
    const session = await auth();
  return (
    <html lang="en">
      <body>
      <Toaster />
      <SessionProvider session={session}>
          <SessionExpirationWatcher/>
          <SplashScreenLayout>{children}</SplashScreenLayout>
      </SessionProvider>
      </body>
    </html>
  );
}

export default RootLayout;
