'use client';
import React, {useEffect, useState} from "react";
import "./globals.scss";
import "../../public/theme/themes/tailwind/tailwind-light/theme.scss";
import 'sweetalert2/src/sweetalert2.scss'
import {Toaster} from "react-hot-toast";
import {SessionProvider} from "next-auth/react";
import SessionExpirationWatcher from "@/lib/SessionExpirationWatcher";
import {Navbar} from "@/components/layout/header/Navbar";
import {Metadata} from "next";
import SplashScreen from "@/components/SplashScreen";

// export const metadata: Metadata = {
//     title: 'My App',
//     description: 'Generated by Next.js',
// };

const RootLayout = ({ children, }: { children: React.ReactNode; }) => {
    const [isLoading, setIsLoading] = useState(true);
    const [isPageReady, setIsPageReady] = useState(false);
    useEffect(() => {
        const handlePageReady = () => {
            setIsPageReady(true);
        };
        console.log(document.readyState)
        // Listen for when the page is fully loaded
        if (document.readyState === 'complete') {
            handlePageReady();
        } else {
            window.addEventListener('load', handlePageReady);
        }

        return () => {
            window.removeEventListener('load', handlePageReady);
        };
    }, []);
  return (
    <html lang="en">
      <body>
      <Toaster />
      <SessionProvider>
          <SessionExpirationWatcher/>

          {!isPageReady ? <SplashScreen /> :
              <div>
                  <Navbar/>
                  {children}
             </div>}
      </SessionProvider>
      </body>
    </html>
  );
}

export default RootLayout;
